### ISSUE TITLE
Incompatible with Python 3.12

### ISSUE THREAD

**Issue by abbasyadollahi** [omergertel/pyformance#80]
The `pyformance` package is incompatible with a freshly installed Python 3.12 virtual environment, unless `setuptools` is also installed.

Steps to reproduce:

```bash
$ python3.12 -m venv env
$ source env/bin/activate
$ pip install pyformance
$ pip list

Package Version
------- -------
pip     24.0
```

```python
Python 3.12.4 (main, Jun  6 2024, 18:26:44) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyformance import MetricsRegistry
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/env/lib/python3.12/site-packages/pyformance/__init__.py", line 1, in <module>
    __import__('pkg_resources').declare_namespace(__name__)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pkg_resources'
```

**Comment by sujeet100** [comment]
is this repository dead?
